server:
  port: 8086

spring:
  datasource:
    url: jdbc:mysql://work:3306/stock_master?useSSL=false&characterEncoding=utf-8&allowPublicKeyRetrieval=true&serverTimezone=GMT%2B8
    username: root
    password: Wqsci2020@
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: work
    port: 6379
    timeout: 1000
    database: 0
    password: 1wo2shi3lixin4redis

logging:
  file:
    name: /logs/stock-service.log
  level:
    root: info
    org.springfromework.web: info
    org.springframework.jdbc: info
